openapi: 3.0.0
x-stoplight:
  id: 00702be226f19
info:
  title: Sample API
  version: 1.0.0
  description: This is a sample API specification.
  contact:
    name: API Support
    email: support@example.com
    url: 'https://example.com'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Orders
    description: Operations related to orders
  - name: Users
    description: Operations related to users

paths:
  /users:
    get:
      operationId: getUsers
      summary: Retrieve a list of users
      description: Fetches a list of users from the system.
      tags:
        - Users
      responses:
        '200':
          description: Successful
      x-stoplight:
        id: y9v4hrgek3z
