openapi: 3.0.0
x-stoplight:
  id: 00702be226f19
info:
  title: Sample API
  version: 1.0.0
  description: This is a sample API specification.
  contact:
    name: API Support
    email: support@example.com
    url: 'https://example.com'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Orders
    description: Operations related to orders
  - name: Users
    description: Operations related to users

paths:
  /users:
    get:
      operationId: getUsers
      summary: Retrieve a list of users
      description: Fetches a list of users from the system.
      tags:
        - Users
      responses:
        '200':
          description: Successful
      x-stoplight:
        id: y9v4hrgek3z

  /orders:
    post:
      operationId: createOrder
      summary: Create a new order
      description: Creates a new order and returns the order ID.
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
              required:
                - productId
                - quantity
      responses:
        '201':
          description: Order created successfully
      x-stoplight:
        id: abcd1234xyz
