extends: spectral:oas
rules:
  operation-operationId-camelCase:
    description: "operationId must be in camelCase format."
    severity: error
    given: "$.paths[*][*].operationId"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z]+([A-Z][a-z0-9]*)*$"

  operation-summary-required:
    description: "Every operation must have a summary."
    severity: warn
    given: "$.paths[*][*]"
    then:
      field: summary
      function: truthy
